authors = ["Lost Saint"]
description = "Format files with dprint through its language server"
id = "dprint"
name = "Dprint"
repository = "https://github.com/Lost-Saint/dprint-zed"
schema_version = 1
version = "0.1.1"

[language_servers.dprint]
name = "dprint"
languages = [
  "JavaScript",
  "TypeScript",
  "TSX",
  "JSON",
  "JSONC",
  "Markdown",
  "TOML",
  "CSS",
  "SCSS",
  "LESS",
  "HTML",
  "Vue.js",
  "Svelte",
  "Astro",
  "Angular",
  "Twig",
  "GraphQL",
  "YAML",
  "PHP",
  "Python",
]
